param([Parameter(Mandatory=$true)][int]$ScannerPid,[Parameter(Mandatory=$true)][string]$OutDir,[int]$DurationSeconds=43200,[int]$IntervalSeconds=300)
$ErrorActionPreference='Continue'
$culture=[System.Globalization.CultureInfo]::InvariantCulture
function MetricValue([string]$Text,[string]$Name){ if([string]::IsNullOrWhiteSpace($Text)){return $null}; foreach($line in ($Text -split "`n")){ $trim=$line.Trim(); if($trim.StartsWith('#') -or $trim.Length -eq 0){continue}; if($trim -match ('^'+[regex]::Escape($Name)+'\s+([-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?)$')){ return [double]::Parse($Matches[1],$culture)}}; return $null }
function MetricSum([string]$Text,[string]$Pattern){ if([string]::IsNullOrWhiteSpace($Text)){return 0.0}; $sum=0.0; foreach($line in ($Text -split "`n")){ $trim=$line.Trim(); if($trim.StartsWith('#') -or $trim.Length -eq 0){continue}; if($trim -match $Pattern){ $parts=$trim -split '\s+'; if($parts.Length -ge 2){$sum += [double]::Parse($parts[-1],$culture)}}}; return $sum }
function F($v){ if($null -eq $v){return ''}; if($v -is [double] -or $v -is [float]){return $v.ToString('0.###',$culture)}; return [string]$v }
$start=Get-Date; $deadline=$start.AddSeconds($DurationSeconds); $tsv=Join-Path $OutDir 'monitor_summary.tsv'
'elapsed_s	time_iso	pid_alive	private_mb	working_set_mb	cpu_s	health_ok	full_p99_ms	full_max_ms	full_over_budget	ml_bg_p99_ms	ml_queue_batches	ml_queue_events	ml_inflight_batches	ml_inflight_events	ml_queue_full	raw_drops	accepted_drops	label_drops	compaction_failures	process_private_metric_mb	process_ws_metric_mb' | Set-Content -LiteralPath $tsv -Encoding UTF8
$i=0
while((Get-Date) -lt $deadline){
 $now=Get-Date; $elapsed=[int]($now-$start).TotalSeconds; $proc=Get-Process -Id $ScannerPid -ErrorAction SilentlyContinue; $alive=$null -ne $proc; $health=$null; $status=$null; $metrics=''; $metricsError=$null
 try{$health=Invoke-RestMethod -Uri 'http://127.0.0.1:8000/healthz' -TimeoutSec 5}catch{$health=@{error=$_.Exception.Message}}
 try{$status=Invoke-RestMethod -Uri 'http://127.0.0.1:8000/api/spread/status' -TimeoutSec 10}catch{$status=@{error=$_.Exception.Message}}
 try{$metrics=(Invoke-WebRequest -Uri 'http://127.0.0.1:8000/metrics' -UseBasicParsing -TimeoutSec 15).Content}catch{$metricsError=$_.Exception.Message}
 $metrics | Set-Content -LiteralPath (Join-Path $OutDir ('metrics_v2_{0:D4}.prom' -f $i)) -Encoding UTF8
 $fullP99=MetricValue $metrics 'scanner_spread_full_cycle_ns_p99'; $fullMax=MetricValue $metrics 'scanner_spread_full_cycle_max_ns'; $fullOver=MetricValue $metrics 'scanner_spread_full_cycle_over_budget_total'; $mlBgP99=MetricValue $metrics 'scanner_ml_background_ns_p99'
 $mlQB=MetricValue $metrics 'scanner_ml_cycle_queue_depth_current'; $mlQE=MetricValue $metrics 'scanner_ml_cycle_queue_events_current'; $mlIB=MetricValue $metrics 'scanner_ml_cycle_batch_inflight_current'; $mlIE=MetricValue $metrics 'scanner_ml_cycle_events_inflight_current'; $mlQF=MetricValue $metrics 'scanner_ml_cycle_queue_full_total'
 $procPriv=MetricValue $metrics 'scanner_process_private_bytes'; $procWs=MetricValue $metrics 'scanner_process_working_set_bytes'; $rawDrops=MetricSum $metrics '^ml_raw_samples_dropped_'; $acceptedDrops=MetricSum $metrics '^ml_accepted_samples_dropped_'; $labelDrops=MetricSum $metrics '^ml_labels_dropped_'; $compFail=MetricSum $metrics '^scanner_ml_dataset_compactions_total\{.*status="failure"'
 $privateMb=if($alive){[math]::Round($proc.PrivateMemorySize64/1MB,2)}else{$null}; $wsMb=if($alive){[math]::Round($proc.WorkingSet64/1MB,2)}else{$null}; $cpu=if($alive){[math]::Round($proc.CPU,2)}else{$null}; $healthOk=if($health -is [string]){$health -eq 'ok'}elseif($health.ok -ne $null){[bool]$health.ok}else{$false}
 [pscustomobject]@{elapsed_s=$elapsed;time_iso=$now.ToUniversalTime().ToString('o');pid=$ScannerPid;pid_alive=$alive;process=if($alive){@{private_mb=$privateMb;working_set_mb=$wsMb;cpu_s=$cpu;start_time=$proc.StartTime}}else{$null};health=$health;status=$status;metrics_error=$metricsError;metrics=@{full_p99_ms=if($fullP99 -ne $null){$fullP99/1e6}else{$null};full_max_ms=if($fullMax -ne $null){$fullMax/1e6}else{$null};full_over_budget=$fullOver;ml_bg_p99_ms=if($mlBgP99 -ne $null){$mlBgP99/1e6}else{$null};ml_queue_batches=$mlQB;ml_queue_events=$mlQE;ml_inflight_batches=$mlIB;ml_inflight_events=$mlIE;ml_queue_full=$mlQF;raw_drops=$rawDrops;accepted_drops=$acceptedDrops;label_drops=$labelDrops;compaction_failures=$compFail;process_private_metric_mb=if($procPriv -ne $null){$procPriv/1MB}else{$null};process_ws_metric_mb=if($procWs -ne $null){$procWs/1MB}else{$null}}} | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath (Join-Path $OutDir ('snapshot_v2_{0:D4}.json' -f $i)) -Encoding UTF8
 $vals=@($elapsed,$now.ToUniversalTime().ToString('o'),$alive,$privateMb,$wsMb,$cpu,$healthOk,$(if($fullP99 -ne $null){$fullP99/1e6}else{$null}),$(if($fullMax -ne $null){$fullMax/1e6}else{$null}),$fullOver,$(if($mlBgP99 -ne $null){$mlBgP99/1e6}else{$null}),$mlQB,$mlQE,$mlIB,$mlIE,$mlQF,$rawDrops,$acceptedDrops,$labelDrops,$compFail,$(if($procPriv -ne $null){$procPriv/1MB}else{$null}),$(if($procWs -ne $null){$procWs/1MB}else{$null})) | ForEach-Object { F $_ }
 Add-Content -LiteralPath $tsv -Value ($vals -join "`t") -Encoding UTF8
 if(-not $alive){break}; $i++; Start-Sleep -Seconds $IntervalSeconds
}
try{Invoke-RestMethod -Method Post -Uri 'http://127.0.0.1:8000/api/admin/shutdown' -TimeoutSec 10 | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath (Join-Path $OutDir 'shutdown_response.json') -Encoding UTF8}catch{$_.Exception.Message | Set-Content -LiteralPath (Join-Path $OutDir 'shutdown_error.txt') -Encoding UTF8}
try{Wait-Process -Id $ScannerPid -Timeout 900 -ErrorAction SilentlyContinue}catch{}
